/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectIdRouteImport } from './routes/project.$id'
import { Route as ApiBlobsSplatRouteImport } from './routes/api/blobs/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdRoute = ProjectIdRouteImport.update({
  id: '/project/$id',
  path: '/project/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBlobsSplatRoute = ApiBlobsSplatRouteImport.update({
  id: '/api/blobs/$',
  path: '/api/blobs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/project/$id': typeof ProjectIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/blobs/$': typeof ApiBlobsSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/project/$id': typeof ProjectIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/blobs/$': typeof ApiBlobsSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/project/$id': typeof ProjectIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/blobs/$': typeof ApiBlobsSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/project/$id' | '/api/auth/$' | '/api/blobs/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/project/$id' | '/api/auth/$' | '/api/blobs/$'
  id: '__root__' | '/' | '/project/$id' | '/api/auth/$' | '/api/blobs/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectIdRoute: typeof ProjectIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiBlobsSplatRoute: typeof ApiBlobsSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$id': {
      id: '/project/$id'
      path: '/project/$id'
      fullPath: '/project/$id'
      preLoaderRoute: typeof ProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/blobs/$': {
      id: '/api/blobs/$'
      path: '/api/blobs/$'
      fullPath: '/api/blobs/$'
      preLoaderRoute: typeof ApiBlobsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectIdRoute: ProjectIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiBlobsSplatRoute: ApiBlobsSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
